
name: VerifyAndTest

on:
  pull_request:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12"]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Analysing the code with black
      run: |
        black --diff --check my_app/
    - name: Analysing the code with isort
      run: |
        isort --check-only --diff my_app/
    - name: Analysing the code with flask8
      run: |
        flake8 my_app/
    - name: Running tests
      run: |
        pytest tests
